# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f137745c5df11ef745f2b14e16e25cf355b880e2a71e8d29fb006f7853455b9162653b044164347f8ed14de67bc469c1decc286d4bf6b63ebb70a5c10b904b52
  google_client_id: 796684580529-e59ol64jvm76ns4ltt6cb6lanvj1nlk9.apps.googleusercontent.com
  google_client_secret: eDb5hVb-g3-f2Iiu0HCyF_LN

test:
  secret_key_base: 9d19761cd459905437ad82a3b257b2706973df878fa34585d378014442b61ca06f4228d1b4bbbe04cc31fce9e6902a70730657823ace46c1142e3e7de88d3b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
